# Generated by Django 3.1.2 on 2020-10-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('compilation', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='label',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
