# Generated by Django 3.1.2 on 2020-10-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20201020_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='year',
            field=models.IntegerField(default=2020),
        ),
        migrations.AddField(
            model_name='track',
            name='year',
            field=models.IntegerField(default=2020),
        ),
    ]
