# Generated by Django 3.1.2 on 2020-10-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20201020_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(upload_to='album_covers'),
        ),
        migrations.AlterField(
            model_name='track',
            name='image',
            field=models.ImageField(upload_to='album_covers'),
        ),
    ]
