# Generated by Django 3.1.2 on 2020-10-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20201020_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='bandcamp',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
