# Generated by Django 3.1.2 on 2020-10-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_album_bandcamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='bandcamp',
            field=models.CharField(max_length=300),
        ),
    ]
