# Generated by Django 3.1.2 on 2020-10-22 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20201022_1905'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Track',
            new_name='CompTrack',
        ),
    ]
