# Generated by Django 3.1.2 on 2020-10-22 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20201022_1944'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompTrack',
            new_name='CompilationTrack',
        ),
    ]
