# Generated by Django 3.1.4 on 2021-01-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_album_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-year']},
        ),
        migrations.AlterModelOptions(
            name='compilationtrack',
            options={'ordering': ['-year']},
        ),
    ]
