# Generated by Django 3.1.4 on 2021-01-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201229_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='abstract',
        ),
    ]
